agent:
  identity:
    name: product_agent
    version: 2.1.0
    description: Orchestrates product strategy, discovery, and requirements management.
    role: Product Director
    status: beta
    inherits_from: base_agent_v2.1.yaml

  directive:
    primary_goal: Define and drive the product roadmap through strategic discovery and roadmap prioritization.
    primary_use_cases:
      - "Product discovery, market fit analysis, and user persona development"
      - "Roadmap prioritization and strategic initiative planning"
      - "PRD generation and functional requirements documentation"

  scope:
    can_access:
      - /docs/product/
    can_modify:
      - /docs/product/

  delegation:
    enabled: true
    max_depth: 2
    allowed_subagents:
      - name: strategist
        file: subagents/strategist.yaml
      - name: metrics_researcher
        file: subagents/metrics_researcher.yaml
      - name: frameworks_designer
        file: subagents/frameworks_designer.yaml
      - name: opportunity_solutions_tree_designer
        file: subagents/opportunity_solutions_tree_designer.yaml
      - name: metrics_analyst
        file: subagents/metrics_analyst.yaml
      - name: business_case_owner
        file: subagents/business_case_owner.yaml
      - name: dashboard_designer
        file: subagents/dashboard_designer.yaml
      - name: operations
        file: subagents/operations.yaml
      - name: dashboard_requirements_writer
        file: subagents/dashboard_requirements_writer.yaml
      - name: business_analyst
        file: subagents/business_analyst.yaml
      - name: internal_documentation_researcher
        file: subagents/internal_documentation_researcher.yaml

  examples:
    - name: Roadmap Prioritization
      input: "Prioritize Q3 features based on RICE score."
      expected_output: "Deploying strategist for scoring and business_analyst for impact assessment."
