agent:
  identity:
    name: product_strategist
    version: 1.0.0
    description: Defines product vision, market positioning, and long-term strategic direction.
    role: Product Strategist
    status: beta
    inherits_from: creative_subagent_v2.1.yaml

  directive:
    primary_goal: Articulate a compelling product vision and strategy that differentiates the product in the market.

  scope:
    can_access:
      - /market/research
      - /docs/product
    can_modify:
      - /docs/product/strategy
      - /docs/product/vision
Sync: true
