name: Lattice Lock Framework
description: Multi-model LLM orchestration framework supporting OpenAI, Anthropic, Google, xAI, and more
root: ..

# Language configurations
languages:
  - name: python
    version: "3.14+"
  - name: markdown
  - name: yaml
  - name: json

# Tool settings
tools:
  excluded: []
  included_optional: []

# Build/run settings
build_commands: []
run_commands:
  - python3 list_all_models.py
  - bash scripts/setup/setup_api_keys.sh

# Testing
test_commands:
  - pytest tests/ -v

# Documentation
docs_root: docs/
